name: Android CI

on: 
  push:
    branches: ["main"]
  pull_request: 
    branches: ["main"]

jobs:
  # 1. TESTS (first filter)
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest
      - name: Upload Test Report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: "**/build/reports/tests/testDebugUnitTest/"
        
# 2. CI - Build to create the enviroment and to run our project only if passed test 
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
          
      - name: Grant execute pemission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew assembleDebug
        env:
          GEMINI_API_KEY: ${{secrets.GEMINI_API_KEY}}
      - name: Upload APK Artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: dogedex-app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
      
# 3. CD - Deploy
  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download APK from build job
        uses: actions/download-artifact@v4
        with:
          name: dogedex-app-debug

      - name: Create Github Release
        id: create_release
        uses: softprops/action-gn-release@v2
        with:
          tag_name: v1.0.${{github.run_number}}
          name: "Dogedex AI - Build $ {{github.run_number}}"
          body: |
            ### 🚀 New Test version
            - Gemini 1.5 frash integration completed.
            - ML Kit models and TensorFlow lite optimized
            - Automatic compilation CI/CD.
          draft: false
          prerelease: false
          files: app_debug.apk
